name: Databricks dbt CI/CD Pipeline

on:
  pull_request:
    branches:
      - test
      - main

jobs:
  deploy-and-run-dbt:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository code
        uses: actions/checkout@v4

      - name: Setup Databricks CLI
        uses: databricks/setup-cli@v0.2.0

      - name: Trigger Databricks TEST dbt Job
        if: github.base_ref == 'test'
        env:
          DATABRICKS_HOST: ${{ secrets.DATABRICKS_TEST_HOST }}
          DATABRICKS_TOKEN: ${{ secrets.DATABRICKS_TEST_TOKEN }}
        run: |
          databricks jobs run-now --job-id 111111111

      - name: Trigger Databricks PROD dbt Job
        if: github.base_ref == 'main' # <-- Nota: si usa base_ref per le PR
        env:
          DATABRICKS_HOST: ${{ secrets.DATABRICKS_PROD_HOST }}
          DATABRICKS_TOKEN: ${{ secrets.DATABRICKS_PROD_TOKEN }}
        run: |
          databricks jobs run-now --job-id 222222222