name: Databricks dbt CI/CD Pipeline

on:
  pull_request:
    branches:
      - test
      - release/*
      - main
    types:
      - opened
      - synchronize
      - reopened
      - closed

jobs:
  dbt-slim-ci:
    name: Run dbt Slim CI with Deferral
    if: github.event.action != 'closed'
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout del codice
      - name: Checkout repository code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      
      # 1.5. Controllo presenza file YML per ogni modello SQL
      - name: Check SQL models have corresponding YML files
        run: |
          echo "Verifica presenza dei file yml per ciascun modello sql"
          MISSING_YML=0

          while read -r sql_file; do
            # Rimuove l'estensione .sql per ottenere il percorso base del modello
            base_path="${sql_file%.sql}"
            
            # Controlla se esiste il rispettivo file .yml o .yaml
            if [ ! -f "${base_path}.yml" ]; then
              echo "::error file=${sql_file}::Il file '${sql_file}' non ha un file YML di documentazione corrispondente (${base_path}.yml o ${base_path}.yaml)!"
              MISSING_YML=1
            fi
          done < <(find models -type f -name "*.sql")

          # Se almeno un file YML manca, interrompe la pipeline
          if [ $MISSING_YML -gt 0 ]; then
            echo "::error::manca file yml."
            exit 1
          fi
          echo "success: Tutti i file SQL hanno il rispettivo file YML."

      # 2. Controllo allineamento branch
      - name: Check if Branch is Up-to-Date with Target
        run: |
          TARGET_BRANCH="${{ github.base_ref }}"
          LAST_COMMIT="${{ github.event.pull_request.head.sha }}"
          echo "Verifica disallineamento rispetto a: $TARGET_BRANCH"
          
          git fetch origin $TARGET_BRANCH
          BEHIND_COUNT=$(git rev-list --count $LAST_COMMIT..origin/$TARGET_BRANCH)

          if [ "$BEHIND_COUNT" -gt 0 ]; then
            echo "::error::Il tuo branch è indietro di $BEHIND_COUNT commit rispetto a '$TARGET_BRANCH'. Fai un merge o un rebase da '$TARGET_BRANCH' prima di eseguire la Pull Request!"
            exit 1
          else
            echo "Il branch sorgente è al pari o più avanti rispetto a '$TARGET_BRANCH'."
          fi
      
      # controllo branch status rispetto a main usando branch release come deploy intermedio
      #  run: |
      #    git fetch origin main
      #    SRC_BRANCH="${{ github.head_ref }}"
      #    TARGET_BRANCH="${{ github.base_ref }}"
      #    LAST_COMMIT="${{ github.event.pull_request.head.sha }}"

      #    git fetch origin $TARGET_BRANCH
      #    echo "Branch Sorgente: $SRC_BRANCH"
      #    echo "Branch Destinazione: $TARGET_BRANCH"

      #    ERRORS=0

      #    Controlla se il branch sorgente è indietro rispetto a main
      #    SRC_BEHIND=$(git rev-list --count $LAST_COMMIT..origin/$TARGET_BRANCH)
      #    if [ "$SRC_BEHIND" -gt 0 ]; then
      #      echo "::error::Il branch sorgente '$SRC_BRANCH' è indietro di $SRC_BEHIND commit rispetto a 'main'."
      #      ERRORS=$((ERRORS + 1))
      #    else
      #      echo "success: Il branch sorgente '$SRC_BRANCH' è allineato con 'main'."
      #    fi
#
      #    Controlla se il branch dindestinazione è indietro rispetto a main
      #    if [ "$TARGET_BRANCH" != "main" ]; then
      #      git fetch origin main
      #      TARGET_BEHIND=$(git rev-list --count origin/$TARGET_BRANCH..origin/main)
      #      if [ "$TARGET_BEHIND" -gt 0 ]; then
      #        echo "::error::Il branch di destinazione '$TARGET_BRANCH' è indietro di $TARGET_BEHIND commit rispetto a 'main'."
      #        ERRORS=$((ERRORS + 1))
      #      else
      #        echo "success: Il branch di destinazione '$TARGET_BRANCH' è allineato con 'main'."
      #      fi
      #    else
      #      echo "La destinazione è 'main' e il controllo è già effettuato"
      #    fi

      #    # Blocco se almeno uno dei due è disallineato
      #    if [ "$ERRORS" -gt 0 ]; then
      #      echo "Allineare il branch source con target là dove è necessario"
      #      exit 1
      #    fi

      # 3. Validazione nome ramo sorgente per main
      - name: Validate Source Branch Name for Main
        if: github.base_ref == 'main'
        run: |
          SRC_BRANCH="${{ github.head_ref }}"
          echo "Branch sorgente della PR: $SRC_BRANCH"
          if [[ "$SRC_BRANCH" != "dev" && ! "$SRC_BRANCH" =~ ^dev/ ]]; then
            echo "::error::Le Pull Request verso 'main' sono consentite solo da 'dev' o rami 'dev/'!"
            exit 1
          fi
        
      #  run: |
      #    SRC_BRANCH="${{ github.head_ref}}"
      #    TARGET_BRANCH="${{ github.base_ref}}"
      #    if [[ "$TARGET_BRANCH" == 'main' ]]; then
      #      if [[ "$SRC_BRANCH" != 'release' && ! "$SRC_BRANCH" =~ ^release/ ]]; then
      #        echo "::error::Le Le pr verso main devono essere aperta solo da release branch"
      #        exit 1
      #      else
      #        echo "il branch di partenza è corretto"
      #      fi
      #    fi
      #    if [[ "$TARGET_BRANCH" == 'release' || "$TARGET_BRANCH" =~ ^release/ ]]; then
      #      if [[ "$SRC_BRANCH" != 'dev' && ! "$SRC_BRANCH" =~ ^dev/ ]]; then
      #        echo "::error::Le Le pr verso release devono essere aperta solo da rami dev o dev/"
      #        exit 1
      #      else
      #        echo "il branch di partenza è corretto"
      #      fi
      #    fi

      # 4. Setup Python
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      # 5. Installazione dipendenze
      - name: Install Dependencies
        run: |
          pip install --upgrade pip
          pip install dbt-databricks databricks-sdk requests

      # 6. Impostazione Variabili d'Ambiente e Generation profiles.yml
      - name: Set Target Environment Variables
        run: |
          PR_SCHEMA="tst_pr_${{ github.event.number }}"
          echo "PR_TEMPORARY_SCHEMA=$PR_SCHEMA" >> $GITHUB_ENV
          echo "DBT_PR_SCHEMA=$PR_SCHEMA" >> $GITHUB_ENV
          echo "DATABRICKS_HOST=${{ secrets.DATABRICKS_HOST }}" >> $GITHUB_ENV
          echo "DATABRICKS_HTTP_PATH=${{ secrets.DBT_HTTP_PATH }}" >> $GITHUB_ENV
          echo "DATABRICKS_TOKEN=${{ secrets.DATABRICKS_TOKEN }}" >> $GITHUB_ENV
          echo "DBT_TARGET=tst" >> $GITHUB_ENV

      - name: Generate profiles.yml
        run: |
          cat <<EOF > profiles.yml
          pipeline_on_databricks:
            target: "${{ env.DBT_TARGET }}"
            outputs:
              tst:
                type: databricks
                host: "${{ env.DATABRICKS_HOST }}"
                http_path: "${{ env.DATABRICKS_HTTP_PATH }}"
                auth_type: token
                token: "${{ env.DATABRICKS_TOKEN }}"
                catalog: "${{ env.PR_TEMPORARY_SCHEMA }}"
                schema: "main"
                threads: 4
          EOF

      # 6.5 Creazione Fisica del Catalogo Temporaneo su Databricks
      - name: Create PR Temporary Catalog
        env:
          DATABRICKS_HOST: ${{ env.DATABRICKS_HOST }}
          DATABRICKS_HTTP_PATH: ${{ env.DATABRICKS_HTTP_PATH }}
          DATABRICKS_TOKEN: ${{ env.DATABRICKS_TOKEN }}
          PR_NUM: ${{ github.event.number }}
        run: |
          python macros/temp_catalog.py --action create

      # 7. Download Manifest da Databricks Volume
      - name: Download Target Manifest from Databricks Volume
        env:
          DATABRICKS_HOST: ${{ env.DATABRICKS_HOST }}
          DATABRICKS_TOKEN: ${{ env.DATABRICKS_TOKEN }}
        run: |
          python macros/get_last_manifest.py

      # 8. Download Dipendenze dbt
      - name: Install dbt Dependencies
        run: |
          dbt deps --profiles-dir .

      # 9. Step 1 - dbt Full Refresh solo sugli incrementali modificati
      - name: Step 1 - dbt Full Refresh (Modified Incremental models)
        env:
          DATABRICKS_HOST: ${{ env.DATABRICKS_HOST }}
          DATABRICKS_HTTP_PATH: ${{ env.DATABRICKS_HTTP_PATH }}
          DATABRICKS_TOKEN: ${{ env.DATABRICKS_TOKEN }}
        run: |
          if [ -f "./target_remote/manifest.json" ]; then
            echo "Step 1: Full Refresh solo sui modelli INCREMENTALI modificati"
            dbt build \
              --fail-fast \
              --full-refresh \
              --defer \
              --state ./target_remote \
              --profiles-dir . \
              --select +state:modified,config.materialized:incremental --exclude leaning_dummy_model+ || echo "Nessun modello incrementale modificato."
          else
            echo "Full Refresh globale degli incrementali se manifest non viene trovato"
            dbt build \
              --fail-fast \
              --full-refresh \
              --profiles-dir . \
              --select config.materialized:incremental --exclude leaning_dummy_model+ || echo "Nessun modello incrementale presente nel progetto."
          fi

      # 10. Step 2 - dbt Build dei modificati + lineage incrementale
      - name: Step2 - dbt Build (Modified models & Incremental lineage)
        env:
          DATABRICKS_HOST: ${{ env.DATABRICKS_HOST }}
          DATABRICKS_HTTP_PATH: ${{ env.DATABRICKS_HTTP_PATH }}
          DATABRICKS_TOKEN: ${{ env.DATABRICKS_TOKEN }}
        run: |
          if [ -f "./target_remote/manifest.json" ]; then
            echo "Step 2: Build di tutti i modelli modificati e della linea incrementale"
            dbt build \
              --fail-fast \
              --defer \
              --state ./target_remote \
              --profiles-dir . \
              --select state:modified+ +state:modified,config.materialized:incremental --exclude leaning_dummy_model+ || echo "Nessun modello da eseguire."
          else
            echo "se manifest non viene trovto"
            dbt build \
              --fail-fast \
              --profiles-dir . \
              --exclude leaning_dummy_model+
          fi

  cleanup-pr-schema:
    name: Drop Temporary PR Catalog
    if: github.event.action == 'closed'
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install Databricks SDK
        run: pip install databricks-sdk

      - name: Drop Ephemeral Catalog
        env:
          DATABRICKS_HOST: ${{ secrets.DATABRICKS_HOST }}
          DATABRICKS_HTTP_PATH: ${{ secrets.DBT_HTTP_PATH }}
          DATABRICKS_TOKEN: ${{ secrets.DATABRICKS_TOKEN }}
          PR_NUM: ${{ github.event.number }}
        run: |
          python macros/temp_catalog.py --action drop